### PR TITLE
Officially closing project

### PR DESCRIPTION
**Pull request by istx25**
I will no longer be maintaining this project. Updated the README to reflect this as well as removed a few other things.

### CODE REVIEW

**Comment by mcansh** [comment]
💔

**Comment by istx25** [comment]
Yeah, never really got into Ghost. Thanks for building this with me. :)

**Comment by istx25** [comment]
If you want I can transfer the project to you if you want to do something with it.

**Comment by istx25** [comment]
It was a cool idea.

**Pull request merged**
